ComponentSelectorOffset (8)

ComponentRangeCount (6)
ComponentRangeShift (8)
ComponentRangeMask  (FF)

ComponentRangeBegin (0)
	ComponentError (GetMPWorkFunction)
	ComponentError (Unregister)
	StdComponentCall (Target)
	ComponentError (Register)
	StdComponentCall (Version)
	StdComponentCall (CanDo)
	StdComponentCall (Close)
	StdComponentCall (Open)
ComponentRangeEnd (0)

ComponentRangeUnused(1)
ComponentRangeUnused(2)
ComponentRangeUnused(3)
ComponentRangeUnused(4)
ComponentRangeUnused(5)

ComponentRangeBegin (6)
	ComponentCall		(Initialize)
	ComponentCall		(HandleNewPacket)
	ComponentCall		(ComputeChunkSize)
	ComponentCall		(AdjustPacketParams)
	ComponentCall		(CopyDataToChunk)
	ComponentCall		(SendPacketList)
	ComponentCall		(GetTimeScaleFromPacket)
	ComponentDelegate	(0x0507)
	ComponentDelegate	(0x0508)
	ComponentCall		(SetInfo)
	ComponentCall		(GetInfo)
	ComponentCall		(HasCharacteristic)
	ComponentCall		(Reset)
ComponentRangeEnd (6)