ComponentSelectorOffset (8)

ComponentRangeCount (6)
ComponentRangeShift (8)
ComponentRangeMask  (FF)

ComponentRangeBegin (0)
  ComponentError    (GetMPWorkFunction)
  ComponentError    (Unregister)
  StdComponentCall  (Target)
  ComponentError    (Register)
  StdComponentCall  (Version)
  StdComponentCall  (CanDo)
  StdComponentCall  (Close)
  StdComponentCall  (Open)
ComponentRangeEnd   (0)

ComponentRangeUnused(1)
ComponentRangeUnused(2)
ComponentRangeUnused(3)
ComponentRangeUnused(4)
ComponentRangeUnused(5)

ComponentRangeBegin (6)
  ComponentCall     (BeginPacketGroup)
  ComponentCall     (EndPacketGroup)
  ComponentCall     (BeginPacket)
  ComponentCall     (EndPacket)
  ComponentCall     (AddPacketLiteralData)
  ComponentCall     (AddPacketSampleData)
  ComponentCall     (AddPacketRepeatedData)
  ComponentCall     (ReleaseRepeatedData)
  ComponentCall     (SetPacketSequenceNumber)
  ComponentCall     (GetPacketSequenceNumber)
  ComponentCall     (SetCallback)
  ComponentCall     (GetCallback)
  ComponentCall     (SetInfo)
  ComponentCall     (GetInfo)
  ComponentCall     (SetPacketTimeStampOffset)
  ComponentCall     (GetPacketTimeStampOffset)
  ComponentCall     (AddPacketSampleData64)
  ComponentCall     (GetSampleData)
  ComponentCall     (AddRepeatPacket)
ComponentRangeEnd   (6)

