ComponentSelectorOffset (6)

ComponentRangeCount (6)

ComponentRangeShift (8)
ComponentRangeMask  (FF)

ComponentRangeBegin (0)
	StdComponentCall  (Target)
	ComponentError    (Register)
	StdComponentCall  (Version)
	StdComponentCall  (CanDo)
	StdComponentCall  (Close)
	StdComponentCall  (Open)
ComponentRangeEnd   (0)

ComponentRangeUnused  (1)
ComponentRangeUnused  (2)
ComponentRangeUnused  (3)
ComponentRangeUnused  (4)
ComponentRangeUnused  (5)

ComponentRangeBegin (6)
	ComponentCall     (Initialize)
	ComponentCall     (PreflightMedia)
	ComponentDelegate (Idle)
	ComponentCall     (SetSampleData)
	ComponentCall     (Flush)
	ComponentCall     (Reset)
	ComponentDelegate (SetInfo)
	ComponentCall     (GetInfo)
	ComponentCall     (SetTimeScale)
	ComponentCall     (GetTimeScale)
	ComponentCall     (SetTimeBase)
	ComponentCall     (GetTimeBase)
	ComponentCall     (HasCharacteristic)
	ComponentDelegate (0x50D)
	ComponentCall     (SetPacketBuilder)
	ComponentCall     (GetPacketBuilder)
	ComponentCall     (SetMediaType)
	ComponentCall     (GetMediaType)
	ComponentCall     (SetMaxPacketSize)
	ComponentCall     (GetMaxPacketSize)
	ComponentCall     (SetMaxPacketDuration)
	ComponentCall     (GetMaxPacketDuration)
	ComponentDelegate (DoUserDialog)
	ComponentDelegate (SetSettingsFromAtomContainerAtAtom)
	ComponentDelegate (GetSettingsIntoAtomContainerAtAtom)
	ComponentDelegate (GetSettingsAsText)
ComponentRangeEnd   (6)